config/routes.rb
Rails.application.routes.draw do
 get "new" => "users#new"
root :to => "users#new"
resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
validates :name, presence: true,length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
@user = User.new
  end
def create
@user = User.new(user_params)
if @user.save
redirect_to @user
else
render 'new'
end
end
public
def user_params
params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
def show
@user = User.find(params[:id])
end
def index
  @users = User.all
end
def edit
  @user = User.find(params[:id])
end
def update
@user = User.find(params[:id])
if @user.update(user_params)
    redirect_to @user
  else
    render 'edit'
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tgus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Editing article</h1>
 
<%= form_for :user, url: user_path(@user), method: :patch do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
  <%= f.label :Name %>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
<%= f.text_field :name %>
</p>
<p>
<%= f.label :emailid %>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
<%= f.text_field :email %>
</p>
</br>
<p>
<%= f.label :password %>
&nbsp &nbsp &nbsp &nbsp &nbsp 
<%= f.password_field :password %>
</p>
<p>
<%= f.label :retype_yourpassword %>
<%= f.password_field :passwordconfirmation %>
</p>
<br>
<p>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
<%= f.submit %>
<% end %>
 
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <tr>
    <th>UserName</th>
    <th>Email</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
<td><%= link_to 'Show', user_path(user) %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1> My rails application</h1>
<br>
<h2>Wecome to reservation form <h2>
<h3> Login</h3>
<%= form_for :user do |f| %>
<% if @user.errors.any? %>
<div id = "error_explanation">
<h2><%= pluralize(@user.errors.count, "error") %>
fill the form correctely <h2>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<p>
<%= f.label :Name %>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
<%= f.text_field :name %>
</p>
<p>
<%= f.label :emailid %>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
<%= f.text_field :email %>
</p>
</b>
<p>
<%= f.label :password %>
&nbsp &nbsp &nbsp &nbsp &nbsp 
<%= f.password_field :password %>
</p>
<p>
<%= f.label :retype_yourpassword %>
<%= f.password_field :passwordconfirmation %>
</p>
<br>
<p>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>username:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>Email_id:</strong>
  <%= @user.email %>
</p>
<br >
<%= link_to 'Back', users_path %>
<%= link_to 'Edit', edit_user_path(@user) %>